# Paths, relative to /code where main.py is run
pairs_path: ../data/processed/arctic/80deg.zarr
parameters: ../configs/parameters/nn_focal.yaml
results_path: ../results/nn/charlie/arctic/80deg/
architecture: ../configs/nn_architecture/it_2L.yaml

train_features: ['siconc', 'sithic', 'sivelv', 'sivelu', 'utau_ai', 'utau_oi', 'vtau_ai', 'vtau_oi']
train_labels: ['sivelv', 'sivelu']

difference_labels: True
zarr_fmt: fmt2
scale_features: True

batch_size: 64
shorten_dataset: 100000

test_fraction: 0.01 # deliberately very small as test data aren't used at this stage