model:
  fc1:
    type: Linear
    args: [999, 32]
  relu1:
    type: GELU
    args: []
  fc2:
    type: Linear
    args: [32, 64]
  relu2:
    type: GELU
    args: []
  fc3:
    type: Linear
    args: [64, 64]
  relu3:
    type: GELU
    args: []
  fc4:
    type: Linear
    args: [64, 32]
  relu4:
    type: GELU
    args: []
  fc5:
    type: Linear
    args: [32, 999]
  
