name: ML
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - anyio=4.10.0
  - appnope=0.1.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=25.1.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - bleach=6.3.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - certifi=2025.11.12
  - cffi=2.0.0
  - cftime=1.6.5
  - charset-normalizer=3.4.4
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.13.11
  - cycler=0.12.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecated=1.3.1
  - donfig=0.8.1.post1
  - executing=2.2.1
  - filelock=3.20.0
  - fmt=12.0.0
  - fonttools=4.61.1
  - freetype=2.14.1
  - fsspec=2025.12.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-crc32c=1.7.1
  - h11=0.16.0
  - html5lib=1.1
  - httpcore=1.0.9
  - httpx=0.28.1
  - idna=3.11
  - ipykernel=6.31.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.3
  - json5=0.12.1
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.9.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.9
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcxx=21.1.7
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libpng=1.6.53
  - libprotobuf=6.31.1
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libtiff=4.7.1
  - libtorch=2.9.1
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.7
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mistune=3.1.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.2
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.6.1
  - nomkl=1.0
  - notebook=7.5.0
  - notebook-shim=0.2.4
  - numcodecs=0.16.5
  - numpy=2.3.5
  - openjpeg=2.5.4
  - openssl=3.6.0
  - optree=0.18.0
  - packaging=25.0
  - pandas=2.3.3
  - pandoc=2.12
  - pandocfilters=1.5.1
  - parso=0.8.5
  - pexpect=4.9.0
  - pillow=12.0.0
  - pip=25.3
  - platformdirs=4.5.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11=3.0.1
  - pybind11-abi=11
  - pybind11-global=3.0.1
  - pycparser=2.23
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.13.11
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=4.0.0
  - python-tzdata=2025.3
  - python_abi=3.13
  - pytorch=2.9.1
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qtconsole=5.7.0
  - qtpy=2.4.3
  - readline=8.2
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.28.0
  - scikit-learn=1.8.0
  - scipy=1.16.3
  - send2trash=1.8.2
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.9.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.3
  - sympy=1.14.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tornado=6.5.3
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.1
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - widgetsnbextension=4.0.14
  - wrapt=1.17.3
  - xarray=2025.12.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zarr=3.1.5
  - zeromq=4.3.5
  - zlib-ng=2.3.2
  - zstd=1.5.7
prefix: /opt/miniconda3/envs/ML
