name: ML
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - blosc=1.21.6=h4190f5b_0
  - bottleneck=1.4.2=py313h540bb41_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - cartopy=0.25.0=py313h42c1672_0
  - certifi=2025.11.12=py313haa95532_0
  - cftime=1.6.5=py313h540bb41_0
  - click=8.2.1=py313haa95532_0
  - colorama=0.4.6=py313haa95532_0
  - contourpy=1.3.3=py313h214f63a_0
  - crc32c=2.7.1=py313h827c3e9_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - donfig=0.8.1.post1=py313haa95532_0
  - expat=2.7.3=h9214b88_0
  - filelock=3.20.0=py313haa95532_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py313h02ab6af_0
  - freetype=2.13.3=h0620614_0
  - fsspec=2025.10.0=py313h4442805_0
  - geos=3.10.6=he74ecf9_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py313h827c3e9_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=10.2.0=he2f9f60_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - importlib-metadata=8.7.0=py313haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - jinja2=3.1.6=py313haa95532_0
  - joblib=1.5.2=py313haa95532_0
  - jpeg=9f=ha349fce_0
  - kiwisolver=1.4.9=py313h03f52e7_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libcurl=8.16.0=h97e0424_0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libmpdec=4.0.0=h827c3e9_0
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libprotobuf=5.29.3=h65a231f_1
  - libssh2=1.11.1=h2addb87_0
  - libtiff=4.5.1=hd77b12b_0
  - libtorch=2.7.0=cpu_mkl_h017a133_100
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown-it-py=4.0.0=py313haa95532_0
  - markupsafe=3.0.2=py313h827c3e9_0
  - matplotlib=3.10.6=py313haa95532_1
  - matplotlib-base=3.10.6=py313h26e45b9_1
  - mdurl=0.1.2=py313haa95532_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py313h0b37514_0
  - mkl_fft=2.1.1=py313hbc2a22c_0
  - mkl_random=1.3.0=py313h42c1672_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py313haa95532_0
  - msgpack-python=1.1.1=py313h5da7b33_0
  - mysql-common=9.3.0=hf582a5b_3
  - mysql-libs=9.3.0=hc0ebf12_3
  - networkx=3.5=py313haa95532_0
  - numcodecs=0.16.3=py313hc78d781_0
  - numexpr=2.14.1=py313h7660c64_0
  - numpy=2.3.5=py313h050da96_0
  - numpy-base=2.3.5=py313h1e017a8_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.18=h543e019_0
  - opentelemetry-api=1.38.0=py313haa95532_0
  - packaging=25.0=py313haa95532_1
  - pandas=2.3.3=py313h42c1672_1
  - pcre2=10.46=h5740b90_0
  - pillow=11.1.0=py313h096bfcc_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - proj=9.3.1=ha107b6e_0
  - pygments=2.19.2=py313haa95532_0
  - pyparsing=3.2.5=py313haa95532_0
  - pyproj=3.6.1=py313h9783e57_1
  - pyqt=6.9.1=py313h12ec796_0
  - pyqt6-sip=13.10.2=py313h630b2a1_0
  - pyshp=3.0.2.post1=py313haa95532_0
  - python=3.13.9=h260b955_100_cp313
  - python-dateutil=2.9.0post0=py313haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=2_cp313
  - pytorch=2.7.0=cpu_mkl_py313he241c65_100
  - pytz=2025.2=py313haa95532_0
  - pyyaml=6.0.3=py313hb9a58be_0
  - qtbase=6.9.2=h06bae2a_5
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - rich=14.2.0=py313haa95532_0
  - scikit-learn=1.7.1=py313hd8cff78_0
  - scipy=1.16.3=py313hbd6d557_0
  - setuptools=80.9.0=py313haa95532_0
  - shapely=2.1.2=py313h0c56243_0
  - shellingham=1.5.4=py313haa95532_0
  - sip=6.12.0=py313h706e071_0
  - six=1.17.0=py313haa95532_0
  - sleef=3.5.1=h8cc25b3_2
  - sqlite=3.51.0=hda9a48d_0
  - sympy=1.14.0=py313haa95532_0
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - threadpoolctl=3.5.0=py313h4442805_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py313h827c3e9_0
  - typer=0.17.4=py313haa95532_1
  - typing-extensions=4.15.0=py313haa95532_0
  - typing_extensions=4.15.0=py313haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py313haa95532_0
  - xarray=2025.10.1=py313haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zarr=3.1.3=py313haa95532_0
  - zipp=3.23.0=py313haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
prefix: C:\Users\charl\miniconda3\envs\ML
