# Paths, relative to /code where main.py is run
pairs_path: ../data/processed/arctic/80deg.zarr
parameters: ../configs/parameters/nn_shrinkage.yaml
results_path: ../results/nn/charlie/80deg/focal/
architecture: ../configs/nn_architecture/it_5L_gelu.yaml
save_val: True

train_features: ['siconc', 'sithic', 'sivelv', 'sivelu', 'utau_ai', 'utau_oi', 'vtau_ai', 'vtau_oi']
train_labels: ['sivelv', 'sivelu']

zarr_fmt: fmt2
difference_labels: True
scale_features: True

batch_size: 64
#shorten_dataset: 100000
test_fraction: 0.01