# Paths, relative to /code where main.py is run
pairs_path: ../data/raw/shortevp.zarr
parameters: ../configs/parameters/nn_base.yaml
results_path: ../results/nn/charlie/mlp-15itr-sivelv/
architecture: ../configs/nn_architecture/it_2L.yaml

train_features: ['siconc', 'sithic', 'sivelv', 'utau_ai', 'utau_oi', 'vtau_ai', 'vtau_oi']
train_labels: ['sivelv']

difference_labels: True
zarr_fmt: fmt2
scale_features: True

loss: MSELoss
optimizer: Adam
learning_rate: 0.001
epochs: 15
batch_size: 64

test_fraction: 0.01 # deliberately very small as test data aren't used at this stage