# Emulating 1200 itr EVP model outputs for latitudes > 80N in DJF predicting sivelv(t+1)-sivelv(t)
# 0: copied over from 80N_Jan 4, and updateted to include DJF data and sequential=False

# Paths, relative to /code where main.py is run
pairs_path: ../data/raw/evp_1200itr_80N_DJF.zarr
# pairs_path: ../data/raw/evp_1200itr_fmt2.zarr
parameters: ../configs/parameters/nn_base.yaml
results_path: ../results/nn/80N_DJF/0/
architecture: ../configs/nn_architecture/it_4L.yaml
save_data: True

# TODO: add batch size, scaler, val frac
train_features: ['sivelv', 'siconc', 'sithic', 'sivelu', 'utau_ai', 'utau_oi', 'vtau_ai', 'vtau_oi', 'lat']
#train_features: ['sivelv']
train_labels: ['sivelv']

difference_labels: True
zarr_fmt: fmt2
scale_features: True
shorten_dataset: 1000000
sequential: False
save_val: True

loss: MSELoss
optimizer: Adam
learning_rate: 0.001
epochs: 30

test_fraction: 0.001 # 