# Emulating 1200 itr EVP model outputs for latitudes > 80N in January predicting sivelv(t+1)-sivelv(t)
# 0: base config, which should do okay as there are onlt ~10k samples which are quite similar

# Paths, relative to /code where main.py is run
pairs_path: ../data/raw/evp_1200itr_80N_Jan.zarr
# pairs_path: ../data/raw/evp_1200itr_fmt2.zarr
parameters: ../configs/parameters/nn_base.yaml
# TODO: make results path build from namelist prefix
results_path: ../results/nn/80N_Jan/0/
architecture: ../configs/nn_architecture/it_3L.yaml
save_data: True

# TODO: add batch size, scaler, val frac
train_features: ['sivelv', 'siconc', 'sithic', 'sivelu', 'utau_ai', 'utau_oi', 'vtau_ai', 'vtau_oi']
#train_features: ['sivelv']
train_labels: ['sivelv']

difference_labels: True
zarr_fmt: fmt2
scale_features: True
shorten_dataset: 10000
sequential: True
save_val: True

loss: MSELoss
optimizer: Adam
learning_rate: 0.001
epochs: 30

test_fraction: 0.001 # 